services:
  pgdatabase:
    image: postgres:15
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pdadmin:
    image: dpage/pgadmin4
    environment:  
    - PGADMIN_DEFAULT_EMAIL=myuser@admin.com
    - PGADMIN_DEFAULT_PASSWORD=mypass
    ports:
      - "8080:80"
  
