services:
  postgres:
    image: postgres:15 # You can specify the version here
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser       # Set your PostgreSQL username
      POSTGRES_PASSWORD: mypassword # Set your PostgreSQL password
      POSTGRES_DB: mydatabase     # Set your PostgreSQL database name
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    ports:
      - "5432:5432" # Expose the default PostgreSQL port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s    # Time between health checks
      timeout: 5s      # Health check timeout
      retries: 5       # Number of retries before considering unhealthy
    restart: always    # Restart the container if it fails

volumes:
  postgres_data:

create serverconnection
docker run -it \
  -e POSTGRES_USER="myuser" \
  -e POSTGRES_PASSWORD="mypassword" \
  -e POSTGRES_DB="ny_taxi" \
  -v d:/data_eng/Zoomcamp_25/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  postgres:15

  codepace -v /workspaces/Zoomcamp_25/ny_taxi_postgres_data:/var/lib/postgresql/data \


  pdadmin 
docker run -d \
  --name pgadmin \
  -e PGADMIN_DEFAULT_EMAIL="myuser@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="mypass" \
  -p 8080:80 \
  dpage/pgadmin4


##docker network
docker network create pg-network

docker run -it \
  -e POSTGRES_USER="myuser" \
  -e POSTGRES_PASSWORD="mypassword" \
  -e POSTGRES_DB="ny_taxi" \
  -v /workspaces/Zoomcamp_25/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  --network=pg-network \
  --name pg-database \
  postgres:15

  docker run -d \
  --name pgadmin \
  -e PGADMIN_DEFAULT_EMAIL="myuser@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="mypass" \
  -p 8080:80 \
  --network=pg-network \
  --name pgadmin-2 \
  dpage/pgadmin4

  URL = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet"
  
  python ingest_data.py \
    --user=myuser
    --password=mypassword
    --host=localhost
    --port=5432
    --database=ny_taxi
    --table_name=yellow_taxi_trips
    --url=${URL}

docker build -t taxi_injest:v001 .


docker run -it \
--network=pg-network\
 taxi_injest:v001 \ 
 --user=myuser \
 --password=mypassword \
 --host=localhost \
 --port=5432 \
 --database=ny_taxi \
 --table_name=yellow_taxi_trips \
 --url= "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet"



